spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meltique?autoReconnect=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: admin
    password: 1111
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        storage_engine: innodb
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show_sql: true

cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    s3:
      bucket: meltique-bucket
    region:
      static: ap-northeast-2
  stack:
    auto: false
